### ISSUE TITLE
Can this be used?

### ISSUE THREAD

**Issue by faisalil** [spion/typescript-workspace-plugin#1]
I know this package was developed as part of a typescript discussion. Can can this be used? or tried? how did you validate it does the job?

**Comment by spion** [comment]
It should be usable, yes. If you open a yarn workspace project that has separate tsconfig.json files and add the plugin to each, it should take effect. Ctrl+click would go to the .d.ts file before, after adding the plugin it should go to the actual source in the definitions.

**Comment by timm-gs** [comment]
Does the plugin need to re-added into each config file if they're using `"extends"`?

Either way I was unable to get it working, though I was trying to use it with namespaced packages:

```json
  "workspace-sources": {
    "@company/*": [
      "packages/*/src"
    ]
  },
```

**Comment by spion** [comment]
Looks like there was a bug that made the plugin not work with TypeScript 2.6. I pushed a fix. Can you check again please?

**Comment by timm-gs** [comment]
I tried version `1.0.4` with TS `2.6.1` in VS Code `1.18.0`.

It still doesn't work with the above config. Are scoped NPM packages working for you?

**Comment by spion** [comment]
Just tried - yes they're working with the same style of sources path you're using.

edit: I'm assuming your packages directory looks like this? 

`@company/pkgname` sources are in `packages/pkgname/src`
`@company/otherpkgname` sources are in `packages/otherpkgname/src`

**Comment by timm-gs** [comment]
@spion Yes, those are the paths.

Is there any way I can debug the plug-in to get any insight on what I might be overlooking / how my setup might be different? Otherwise I can try to create a minimal reproduction case and share that one with you. Maybe there is another subtle difference in my config that breaks this (for example the nested `tsconfig.json` files in each package?).

**Comment by spion** [comment]
Yes

You can export an environment variable 

    export TSS_LOG="-level verbose -file /tmp/tss.log"

then run vscode and load your project. Afterwards you can grep the console:

    tail -f /tmp/tss.log | cat -v | grep 'typescript-workspace-plugin '

and see if you get any output (the plugin has a few log lines)

**Comment by spion** [comment]
One thing that sometimes happens is that... if you use the vscode-bundled typescript version in a project instead of the project's version, the plugin can't be found. To make it work you'd need to switch to a workspace-installed typescript version. That would be the most likely explanation I can think of - in that case you probably wont get any lines in the log (or get a failure to find the plugin)

**Comment by timm-gs** [comment]
@spion Turns out that I was indeed using the bundled TypeScript version (which currently is the most recent TS 2.6.1, so I didn't notice the discrepancy).

Now it works. And it is great to work with! Thanks a lot for putting this into the world!
